version: "3"
services:
  boathouse-calculator:
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      ROOT_PASSWORD: root123
    image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-opvscode:latest
    networks:
    - smartide-network
    ports:
    - 3001:3001
    - 7000:3000
    - "7022:22"
    restart: always
    volumes:
    - .:/home/project
    - $HOME/.ssh:/root/.ssh
    - /Users/jasonchen/.gitconfig:/root/.gitconfig
networks:
  smartide-network:
    external: true
