apiVersion: v1
kind: Service
metadata:
  labels:
    service: calculator
    app.kubernetes.io/name: calculator
  name: calculator
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    service: calculator
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: calculator
  name: calculator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: calculator
        app.kubernetes.io/component: calculator
        app: calculator
        service: calculator
    spec:
      containers:
      - image: uxxpapez1046.azurecr.cn/calculator:latest
        name: calculator
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always