apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: boathouse-calculator-pipeline
spec:
  params:
    - name: IMAGE_NAME
      description: The image on which builds will run
      default: boathouse-calculator:latest
    - name: DOCKER_USER
      type: string
    - name: DOCKER_PASS
      type: string
    - name: DOCKER_REGISTRY
      type: string
      default: "docker.io"
  resources:
    - name: source
      type: git
  tasks:
    - name: build
      taskRef:
        name: bh-build-docker
      params:
        - name: IMAGE_NAME
          value: $(params.IMAGE_NAME)
      resources:
        inputs:
          - name: source
            resource: source
    - name: push
      image: quay.io/buildah/stable
      command: ['buildah', 'push', '--creds=$(params.DOCKER_USER):$(params.DOCKER_PASS)', '--tls-verify=false', '$(params.DOCKER_REGISTRY)/$(params.DOCKER_USER)/$(params.IMAGE_NAME)', 'docker://$(params.DOCKER_REGISTRY)/$(params.DOCKER_USER)/$(params.IMAGE_NAME)']
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
      securityContext:
        privileged: true
    - name: deploy
      runAfter: [build]
      taskRef:
        name: bh-deploy-kubectl
      resources:
        inputs:
          - name: source
            resource: source
